---
- name: Install and configure Prometheus
  hosts: all
  tasks:
    - name: Add GPG key for the Prometheus repository (Ubuntu)
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Prometheus APT repository (Ubuntu)
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
      when: ansible_distribution == "Ubuntu"

    - name: Install Prometheus (Ubuntu)
      ansible.builtin.apt:
        name: prometheus
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Enable and start Prometheus service (Ubuntu)
      ansible.builtin.service:
        name: prometheus
        enabled: yes
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Open port 9090 for Prometheus (Ubuntu)
      ansible.builtin.ufw:
        rule: allow
        port: 9090
        proto: tcp
        state: enabled
      when: ansible_distribution == "Ubuntu"

    - name: Download Prometheus (CentOS)
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
      when: ansible_distribution == "CentOS"

    - name: Extract Prometheus (CentOS)
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus user (CentOS)
      ansible.builtin.user:
        name: prometheus
        state: present
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus directory (CentOS)
      ansible.builtin.file:
        path: /opt/prometheus
        state: directory
      when: ansible_distribution == "CentOS"

    - name: Move Prometheus binaries (CentOS)
      ansible.builtin.command: mv /tmp/prometheus-2.30.0.linux-amd64/* /opt/prometheus/
      when: ansible_distribution == "CentOS"

    - name: Set ownership and permissions for Prometheus (CentOS)
      ansible.builtin.file:
        path: /opt/prometheus
        owner: prometheus
        group: prometheus
        mode: '0755'
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus service file (CentOS)
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      when: ansible_distribution == "CentOS"

    - name: Reload systemd (CentOS)
      ansible.builtin.command: systemctl daemon-reload
      when: ansible_distribution == "CentOS"

    - name: Start Prometheus service (CentOS)
      ansible.builtin.service:
        name: prometheus
        enabled: yes
        state: started
      when: ansible_distribution == "CentOS"

    - name: Open Firewall Port for Prometheus (CentOS)
      ansible.builtin.firewalld:
        port: 9090/tcp
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: Ensure Firewall Rule Reloaded (CentOS)
      ansible.builtin.firewalld:
        state: reloaded
      when: ansible_distribution == "CentOS"

    - name: Enable Prometheus on system boot (CentOS)
      ansible.builtin.service:
        name: prometheus
        enabled: yes
      when: ansible_distribution == "CentOS"
